create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  sku text not null unique,
  category text not null default 'Mystery Scoop',
  stock_quantity integer not null default 0,
  unit_cost numeric(12, 2) not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.scoop_types (
  id bigint generated by default as identity primary key,
  name text not null unique,
  price numeric(12, 2) not null default 0,
  sort_order integer not null default 0
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  customer_name text not null,
  customer_phone text not null default '',
  customer_address text not null default '',
  scoop_type_id bigint references public.scoop_types(id) on delete set null,
  scoop_name_snapshot text not null,
  scoop_price numeric(12, 2) not null default 0 check (scoop_price >= 0),
  gift_count integer not null default 0 check (gift_count >= 0),
  product_cost numeric(12, 2) not null default 0 check (product_cost >= 0),
  delivery_cost numeric(12, 2),
  packaging_cost numeric(12, 2),
  net_profit numeric(12, 2) not null default 0,
  delivery_status text not null default 'pending'
    check (delivery_status in ('pending', 'delivering', 'delivered', 'cancelled')),
  payment_status text not null default 'unpaid'
    check (payment_status in ('unpaid', 'partial', 'paid')),
  ordered_at date not null,
  delivery_date date,
  created_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete restrict,
  product_name_snapshot text not null,
  quantity integer not null check (quantity > 0),
  unit_cost_snapshot numeric(12, 2) not null default 0 check (unit_cost_snapshot >= 0),
  line_cost numeric(12, 2) not null default 0 check (line_cost >= 0),
  created_at timestamptz not null default now()
);

create table if not exists public.stock_movements (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  quantity_delta integer not null,
  reason text not null,
  note text,
  unit_cost_snapshot numeric(12, 2),
  movement_value numeric(12, 2),
  created_at timestamptz not null default now()
);

create table if not exists public.expenses (
  id bigint generated by default as identity primary key,
  category text not null,
  description text not null,
  amount numeric(12, 2) not null check (amount >= 0),
  spent_at date not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_products_name on public.products(name);
create index if not exists idx_orders_ordered_at on public.orders(ordered_at desc);
create index if not exists idx_order_items_order_id on public.order_items(order_id);
create index if not exists idx_stock_movements_created_at on public.stock_movements(created_at desc);
create index if not exists idx_stock_movements_product_id on public.stock_movements(product_id);
create index if not exists idx_expenses_spent_at on public.expenses(spent_at desc);
create index if not exists idx_scoop_types_sort_order on public.scoop_types(sort_order asc);

drop trigger if exists products_set_updated_at on public.products;
create trigger products_set_updated_at
before update on public.products
for each row
execute function public.set_updated_at();

insert into public.scoop_types (name, price, sort_order)
values
  ('Small', 0, 1),
  ('Medium', 0, 2),
  ('Large', 0, 3),
  ('Custom', 0, 4)
on conflict (name) do nothing;

alter table public.products enable row level security;
alter table public.scoop_types enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.stock_movements enable row level security;
alter table public.expenses enable row level security;

grant usage on schema public to anon, authenticated;
grant select, insert, update, delete on all tables in schema public to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

drop policy if exists "products_full_access" on public.products;
create policy "products_full_access"
on public.products
for all
to anon, authenticated
using (true)
with check (true);

drop policy if exists "scoop_types_full_access" on public.scoop_types;
create policy "scoop_types_full_access"
on public.scoop_types
for all
to anon, authenticated
using (true)
with check (true);

drop policy if exists "orders_full_access" on public.orders;
create policy "orders_full_access"
on public.orders
for all
to anon, authenticated
using (true)
with check (true);

drop policy if exists "order_items_full_access" on public.order_items;
create policy "order_items_full_access"
on public.order_items
for all
to anon, authenticated
using (true)
with check (true);

drop policy if exists "stock_movements_full_access" on public.stock_movements;
create policy "stock_movements_full_access"
on public.stock_movements
for all
to anon, authenticated
using (true)
with check (true);

drop policy if exists "expenses_full_access" on public.expenses;
create policy "expenses_full_access"
on public.expenses
for all
to anon, authenticated
using (true)
with check (true);
