create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  sku text not null unique,
  slug text unique,
  category text not null default 'Mystery Scoop',
  category_id bigint,
  description text,
  base_price numeric(12, 2) not null default 0,
  selling_price numeric(12, 2) not null default 0,
  view_name text,
  active boolean not null default true,
  website_visible boolean not null default true,
  primary_image_url text,
  available_colours text[] not null default '{}',
  sort_order integer not null default 0,
  total_purchased_quantity integer not null default 0,
  stock_quantity integer not null default 0,
  unit_cost numeric(12, 2) not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  slug text not null unique,
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.collections (
  id bigint generated by default as identity primary key,
  name text not null unique,
  slug text not null unique,
  description text,
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.product_collections (
  product_id bigint not null references public.products(id) on delete cascade,
  collection_id bigint not null references public.collections(id) on delete cascade,
  primary key (product_id, collection_id)
);

create table if not exists public.product_images (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  url text not null,
  alt_text text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.discounts (
  id bigint generated by default as identity primary key,
  target_type text not null
    check (target_type in ('product', 'category', 'collection')),
  target_id bigint not null,
  amount numeric not null,
  type text not null
    check (type in ('fixed', 'percent')),
  start_at timestamptz,
  end_at timestamptz,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.scoop_types (
  id bigint generated by default as identity primary key,
  name text not null unique,
  price numeric(12, 2) not null default 0,
  sort_order integer not null default 0
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  customer_name text not null,
  customer_phone text not null default '',
  customer_address text not null default '',
  scoop_type_id bigint references public.scoop_types(id) on delete set null,
  scoop_name_snapshot text not null,
  scoop_price numeric(12, 2) not null default 0 check (scoop_price >= 0),
  gift_count integer not null default 0 check (gift_count >= 0),
  product_cost numeric(12, 2) not null default 0 check (product_cost >= 0),
  delivery_cost numeric(12, 2),
  packaging_cost numeric(12, 2),
  net_profit numeric(12, 2) not null default 0,
  delivery_status text not null default 'pending'
    check (delivery_status in ('pending', 'delivering', 'delivered', 'cancelled')),
  payment_status text not null default 'unpaid'
    check (payment_status in ('unpaid', 'partial', 'paid')),
  order_source text not null default 'dashboard'
    check (order_source in ('dashboard', 'website')),
  ordered_at date not null,
  delivery_date date,
  created_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete restrict,
  product_name_snapshot text not null,
  quantity integer not null check (quantity > 0),
  unit_cost_snapshot numeric(12, 2) not null default 0 check (unit_cost_snapshot >= 0),
  line_cost numeric(12, 2) not null default 0 check (line_cost >= 0),
  created_at timestamptz not null default now()
);

create table if not exists public.stock_movements (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  quantity_delta integer not null,
  reason text not null,
  note text,
  unit_cost_snapshot numeric(12, 2),
  movement_value numeric(12, 2),
  created_at timestamptz not null default now()
);

create table if not exists public.expenses (
  id bigint generated by default as identity primary key,
  category text not null,
  description text not null,
  amount numeric(12, 2) not null check (amount >= 0),
  spent_at date not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_products_name on public.products(name);
create index if not exists idx_products_slug on public.products(slug);
create index if not exists idx_products_category_id on public.products(category_id);
create index if not exists idx_orders_ordered_at on public.orders(ordered_at desc);
create index if not exists idx_orders_order_source on public.orders(order_source);
create index if not exists idx_order_items_order_id on public.order_items(order_id);
create index if not exists idx_stock_movements_created_at on public.stock_movements(created_at desc);
create index if not exists idx_stock_movements_product_id on public.stock_movements(product_id);
create index if not exists idx_expenses_spent_at on public.expenses(spent_at desc);
create index if not exists idx_scoop_types_sort_order on public.scoop_types(sort_order asc);
create index if not exists idx_categories_sort_order on public.categories(sort_order asc);
create index if not exists idx_collections_sort_order on public.collections(sort_order asc);
create index if not exists idx_product_images_product_id on public.product_images(product_id);
create index if not exists idx_discounts_target on public.discounts(target_type, target_id);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'products_category_id_fkey'
  ) then
    alter table public.products
      add constraint products_category_id_fkey
      foreign key (category_id) references public.categories(id) on delete set null;
  end if;
end $$;

drop trigger if exists products_set_updated_at on public.products;
create trigger products_set_updated_at
before update on public.products
for each row
execute function public.set_updated_at();

insert into public.scoop_types (name, price, sort_order)
values
  ('Small', 0, 1),
  ('Medium', 0, 2),
  ('Large', 0, 3),
  ('Custom', 0, 4),
  ('Small Custom', 0, 5),
  ('Medium Custom', 0, 6),
  ('Large Custom', 0, 7)
on conflict (name) do nothing;

alter table public.products enable row level security;
alter table public.categories enable row level security;
alter table public.collections enable row level security;
alter table public.product_collections enable row level security;
alter table public.product_images enable row level security;
alter table public.discounts enable row level security;
alter table public.scoop_types enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.stock_movements enable row level security;
alter table public.expenses enable row level security;

grant usage on schema public to anon, authenticated;
grant select, insert, update, delete on all tables in schema public to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

drop policy if exists "products_full_access" on public.products;
create policy "products_full_access"
on public.products
for all
to anon, authenticated
using (true)
with check (true);

drop policy if exists "categories_full_access" on public.categories;
create policy "categories_full_access"
on public.categories
for all
to anon, authenticated
using (true)
with check (true);

drop policy if exists "collections_full_access" on public.collections;
create policy "collections_full_access"
on public.collections
for all
to anon, authenticated
using (true)
with check (true);

drop policy if exists "product_collections_full_access" on public.product_collections;
create policy "product_collections_full_access"
on public.product_collections
for all
to anon, authenticated
using (true)
with check (true);

drop policy if exists "product_images_full_access" on public.product_images;
create policy "product_images_full_access"
on public.product_images
for all
to anon, authenticated
using (true)
with check (true);

drop policy if exists "discounts_full_access" on public.discounts;
create policy "discounts_full_access"
on public.discounts
for all
to anon, authenticated
using (true)
with check (true);

drop policy if exists "scoop_types_full_access" on public.scoop_types;
create policy "scoop_types_full_access"
on public.scoop_types
for all
to anon, authenticated
using (true)
with check (true);

drop policy if exists "orders_full_access" on public.orders;
create policy "orders_full_access"
on public.orders
for all
to anon, authenticated
using (true)
with check (true);

drop policy if exists "order_items_full_access" on public.order_items;
create policy "order_items_full_access"
on public.order_items
for all
to anon, authenticated
using (true)
with check (true);

drop policy if exists "stock_movements_full_access" on public.stock_movements;
create policy "stock_movements_full_access"
on public.stock_movements
for all
to anon, authenticated
using (true)
with check (true);

drop policy if exists "expenses_full_access" on public.expenses;
create policy "expenses_full_access"
on public.expenses
for all
to anon, authenticated
using (true)
with check (true);
